

export const GET_CATEGORY_ALL='GET_CATEGORY_ALL';

export const GET_CATEGORY_ALL_LOADING='GET_CATEGORY_ALL_LOADING';

export const GET_CATEGORY_ALL_SUCCESS='GET_CATEGORY_ALL_SUCCESS';

export const GET_CATEGORY_ALL_ERROR='GET_CATEGORY_ALL_ERROR';



export const GET_CATEGORY_DETAIL='GET_CATEGORY_DETAIL';
export const GET_CATEGORY_DETAIL_LOADING='GET_CATEGORY_DETAIL_LOADING';
export const GET_CATEGORY_DETAIL_SUCCESS='GET_CATEGORY_DETAIL_SUCCESS';
export const GET_CATEGORY_DETAIL_ERROR='GET_CATEGORY_DETAIL_ERROR';