export const GET_CODE="GET_CODE";

export const GET_QUESTION_ERROR_RULES='GET_QUESTION_ERROR_RULES';



export const GET_USER_ID_SUCCESS='GET_USER_ID_SUCCESS';


export const GET_USER_ID_ERROR='GET_USER_ID_ERROR';