export const LOGIN_USER='LOGIN_USER';
export const LOGIN_USER_LOADING='LOGIN_USER_LOADING';
export const LOGIN_USER_SUCCESS='LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR='LOGIN_USER_ERROR';



export const LOGOUT_USER='LOGOUT_USER';
export const LOGOUT_USER_LOADING='LOGOUT_USER_LOADING';
export const LOGOUT_USER_SUCCESS='LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_ERROR='LOGOUT_USER_ERROR';


export const GET_USER='GET_USER';


export const RESET_MESSAGE_USER='RESET_MESSAGE_USER';





export const GET_RULES='GET_RULES';