export const CODE_ERROR='CODE_ERROR';

export const QUESTION_START='QUESTION_START';

export const RESET_MESSAGE='RESET_MESSAGE';



export const GET_COURSE_LOADING='GET_COURSE_LOADING';

export const GET_COURSE_SUCCESS='GET_COURSE_SUCCESS';
export const GET_COURSE_ERROR='GET_COURSE_ERROR';

export const GET_COURSE='GET_COURSE';