export const GET_QUESTION_ALL='GET_QUESTION_ALL'
export const GET_QUESTION_ALL_LOADING='GET_QUESTION_ALL_LOADING'
export const GET_QUESTION_ALL_SUCCESS='GET_QUESTION_ALL_SUCCESS'
export const GET_QUESTION_ALL_ERROR='GET_QUESTION_ALL_ERROR'



export const GET_QUESTION_LOADING='GET_QUESTION_LOADING'
export const GET_QUESTION_ERROR='GET_QUESTION_ERROR'
export const GET_QUESTION_SUCCESS='GET_QUESTION_SUCCESS'
export const RESET_QUESTION_SUCCESS='RESET_QUESTION_SUCCESS'


export const GET_QUESTION_SUCCESS_ERROR='GET_QUESTION_SUCCESS_ERROR';


export const GET_KET_QUA_SUCCESS='GET_KET_QUA_SUCCESS';

export const ERROR_SERVER='ERROR_SERVER';